version: '3'

services:
  postgres-training-diary:
    image: postgres:latest
    container_name: postgres-coworking-service
    environment:
      POSTGRES_DB: coworking-service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always