database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/coworking-service
  username: user
  password: password
  default:
    schema: service
  test:
    databaseName: coworking-service-test
    username: test
    password: test

liquibase:
  schema: service
  changelog: db/changelog/changelog.xml
  test:
    changelog: db/changelog/changelog_test.xml

#hibernate:
#  dialect: org.hibernate.dialect.PostgreSQLDialect

